### ISSUE TITLE
AddJsonPlatformBundle not working on iOS

### ISSUE THREAD

**Issue by benlings** [shinyorg/ConfigurationExtensions#1] opened 2022-03-25 12:50 UTC
I've added this to a Xamarin.Forms application:

```
<PackageReference Include="Shiny.Extensions.Configuration" Version="1.1.4" />
```

Then in the `ShinyStartup` subclass's `ConfigureServices` I call

```
           var config = new ConfigurationBuilder()
                .AddJsonPlatformBundle("appsettings.json", optional: false)
                .Build();
```

However, if I step into `AddJsonPlatformBundle`, the platform-specific code isn't called. It looks like the `#if` condition isn't being met.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/303436/160122774-04e7cb4d-e076-4c26-ac89-87ae19c5db4c.png">

This happens when building for iOS device + simulator, using Rider 2021.3.2 and Xamarin.iOS 15.4.0.0.

**Comment by aritchie** [comment] 2022-03-25 13:26
You have to have a compile target in order to get those sections to become part of the compiler.  These get switched at compile time for the platform anyhow. 

Please send a reproducible sample.

**Comment by aritchie** [comment] 2022-03-29 13:40
This has been resolved in the latest preview.  Please provide a sample in the future.

**Closed as completed by aritchie** 2022-03-29 13:40 UTC

**Comment by paulirwin** [comment] 2023-02-13 16:43
@aritchie What is the status of this fix? v1.1.1 on NuGet seems to be the only non-preview version and is broken on iOS. Could we get a fixed version of v1.1.x or is there a workaround?

Also there continue to be preview builds published but no corresponding git commits in this repo that I can see, which makes me apprehensive about using a preview release without being able to see the source code. Thanks in advance for any solution to get iOS working for this.

**Comment by aritchie** [comment] 2023-02-13 19:22
It moved over to the main shinyorg/shiny repo several months ago and has received all bugfixes there.

**Comment by paulirwin** [comment] 2023-02-13 20:05
@aritchie Ah good to know, thanks. That was not clear from this repo. I'd suggest archiving this repo and putting a note in the README. 

Any indication on when the latest builds are expected to come out of preview?

**Comment by aritchie** [comment] 2023-02-13 20:13
I'm a busy guy and a lot of people use my stuff.  There are lots of things I could be doing.

As to when it exits preview, I'll give the same answer I give everyone - when it is done.
